
export const C = {
  bg: '#08151b',
  surface: '#0d1a22',
  surfaceHigh: '#152028',
  surfaceHighest: '#1f2c32',
  border: 'rgba(172,199,253,0.15)',
  borderBright: 'rgba(172,199,253,0.4)',
  primary: '#acc7fd',
  green: '#2ae500',
  greenDim: '#d7ffc5',
  amber: '#c7cf00',
  text: '#d7e4ed',
  textDim: '#8e9aaa',
  textMuted: '#3a4e5c',
};

export const effects = [
  {
    slug: 'asciikit', name: 'ASCIIKit', label: 'ASCIIKIT',
    description: 'Advanced text-based visual rendering engine. Converts raster images into animated character matrices with edge detection.',
    version: '2.4.1', latency: '12ms', stability: null,
    tags: ['SHADER', 'CPU_ACC'],
    badge: { label: 'STATUS: STABLE', color: C.primary },
    accent: '#acc7fd',
    icon: '▤',
  },
  {
    slug: 'baby-track', name: 'BabyTrack', label: 'BABYTRACK',
    description: 'Neural motion analysis and skeletal tracking. Optimized for real-time blob detection via webcam or video input.',
    version: '0.9.0-BETA', latency: null, stability: '84%',
    tags: ['NEURAL', 'REALTIME'],
    badge: { label: 'STATUS: LIVE', color: C.green },
    accent: '#2ae500',
    icon: '⊕',
  },
  {
    slug: 'blur-suite', name: 'BlurSuite', label: 'BLURSUITE',
    description: 'Radial, zoom, linear, and wave blur kernels. Simulates motion, depth-of-field, and optical distortion per-pixel.',
    version: '1.8.2', latency: '8ms', stability: null,
    tags: ['KERNEL', 'CPU_ACC'],
    badge: { label: 'STATUS: STABLE', color: C.primary },
    accent: '#60a5fa',
    icon: '≈',
  },
  {
    slug: 'glassify', name: 'Glassify', label: 'GLASSIFY',
    description: 'Layered glass distortion engine. Six refraction modes — Radial, Glitch, Stripe, Organic, Ripple — with per-param control.',
    version: '1.1.0', latency: '18ms', stability: null,
    tags: ['GPU_OPT', 'DYNAMIC'],
    badge: { label: 'STATUS: EXPERIMENTAL', color: C.amber },
    accent: '#67e8f9',
    icon: '◊',
  },
  {
    slug: 'image-track', name: 'ImageTrack', label: 'IMAGETRACK',
    description: 'Static blob detection with animated connection graph. Affinity scoring by hue, area, and proximity similarity.',
    version: '1.3.0', latency: '24ms', stability: null,
    tags: ['NEURAL', 'TENSOR'],
    badge: { label: 'STATUS: STABLE', color: C.primary },
    accent: '#f87171',
    icon: '⌖',
  },
  {
    slug: 'loopflow', name: 'LoopFlow', label: 'LOOPFLOW',
    description: 'Infinite Droste recursive zoom. The image contains itself at every depth. Continuous animation with full iteration control.',
    version: '0.8.1', latency: null, stability: '91%',
    tags: ['RECURSIVE', 'SHADER'],
    badge: { label: 'STATUS: EXPERIMENTAL', color: C.amber },
    accent: '#818cf8',
    icon: '⥀',
  },
  {
    slug: 'recolor', name: 'ReColor', label: 'RECOLOR',
    description: 'HSL hue remapping engine with animated color cycling. Gradient-map duotone and span-shift modes.',
    version: '2.0.0', latency: '6ms', stability: null,
    tags: ['HSL_MAP', 'ANIMATED'],
    badge: { label: 'STATUS: STABLE', color: C.primary },
    accent: '#fb923c',
    icon: '◐',
  },
  {
    slug: 'retroman', name: 'Retroman', label: 'RETROMAN',
    description: 'Two-color dithering engine. Floyd-Steinberg, Atkinson, Bayer, and blue-noise algorithms with custom foreground/background.',
    version: '1.5.0', latency: '4ms', stability: null,
    tags: ['DITHER', 'STATIC'],
    badge: { label: 'STATUS: STABLE', color: C.primary },
    accent: '#c084fc',
    icon: '▦',
  },
  {
    slug: 'scanline', name: 'Scanline', label: 'SCANLINE',
    description: 'CRT and VHS emulator. Phosphor flicker, chroma aberration, tracking bands, and digital block corruption.',
    version: '1.2.0', latency: null, stability: null,
    tags: ['SIGNAL', 'REALTIME'],
    badge: { label: 'STATUS: STABLE', color: C.primary },
    accent: '#34d399',
    icon: '≡',
  },
  {
    slug: 'super-g', name: 'Super-G', label: 'SUPER-G',
    description: 'Stochastic glitch art engine. RGB channel splits, image block displacement, stripe corruption, and scanline jitter.',
    version: '3.1.2', latency: '2ms', stability: null,
    tags: ['GLITCH', 'STOCHASTIC'],
    badge: { label: 'STATUS: STABLE', color: C.primary },
    accent: '#f472b6',
    icon: '↯',
  },
  {
    slug: 'tonekit', name: 'ToneKit', label: 'TONEKIT',
    description: 'Converts image luminosity into repeating geometric shapes — dots, crosses, rings, spirals. Classic halftone engine.',
    version: '2.2.0', latency: '10ms', stability: null,
    tags: ['HALFTONE', 'VECTOR'],
    badge: { label: 'STATUS: POPULAR', color: C.green },
    accent: '#a3e635',
    icon: '░',
  },
];
